### ISSUE TITLE
Installed ver 0.12.2 won't let me enable

### ISSUE THREAD

**Issue by twixarr** [michaeldegroot/cats-blender-plugin#98] opened 2019-01-16 04:40 UTC
I just installed the latest version and it won't let me enable it

https://ibb.co/27NdmGX

**Comment by twixarr** [comment] 2019-01-16 05:33
OK as it turns out it there was a addon clash with whatever the crap i had enabled and i had over 30 blender addons enabled, i turned them ALL off and cats let me enable it HOWEVER...
i'd like to request a feature update: can you make it so that when you enable it that it ONLY initializes on next blender boot up? because all those addons i had were necessary to me.
Thanks.

**Comment by twixarr** [comment] 2019-01-16 05:58
...And now i've discovered it wasn't the native blender addons
it was one of these
https://imgur.com/a/dSwj5F9

**Comment by Darkblader24** [comment] 2019-01-16 09:44
Oh interesting. This might be caused by one of the addons with "Tools" in the name. Can you check if one of the addons in your addon folder is inside a folder named tools?

**Comment by Darkblader24** [comment] 2019-03-22 13:17
I will close this because of no answer. If the issue still persists, please open this.

**Closed by Darkblader24** 2019-03-22 13:17 UTC
